import type { Palette } from "./types";

/** Paint schemes. `wear` drives procedural grime and roughness variation. */

export const DEFAULT_PALETTE: Palette = {
  name: "Workshop Grey",
  primary: "#c8ccd4",
  secondary: "#7b8595",
  accent: "#ffb547",
  trim: "#2c3542",
  glass: "#7fd7ff",
  emissive: "#4ee1ff",
  wear: 0.25,
};

export const PALETTES: readonly Palette[] = [
  DEFAULT_PALETTE,
  {
    name: "Sentinel Cold",
    primary: "#5f7794",
    secondary: "#33445c",
    accent: "#8fd8ff",
    trim: "#1a2230",
    glass: "#b9f2ff",
    emissive: "#5fd0ff",
    wear: 0.15,
  },
  {
    name: "Exotic Bloom",
    primary: "#3f2f5c",
    secondary: "#8a5cc9",
    accent: "#ffd166",
    trim: "#241a38",
    glass: "#ffc9f0",
    emissive: "#c48bff",
    wear: 0.1,
  },
  {
    name: "Combat Red",
    primary: "#8c2436",
    secondary: "#3a3f4a",
    accent: "#ffb547",
    trim: "#15181d",
    glass: "#ff8f9f",
    emissive: "#ff4d6d",
    wear: 0.45,
  },
  {
    name: "Rebel White",
    primary: "#eef1f5",
    secondary: "#b9c0cb",
    accent: "#d63b3b",
    trim: "#3a4150",
    glass: "#9fd8ff",
    emissive: "#ff8a5c",
    wear: 0.2,
  },
  {
    name: "Imperial Black",
    primary: "#20242c",
    secondary: "#3b434f",
    accent: "#6ea8ff",
    trim: "#0d0f13",
    glass: "#4a6b8c",
    emissive: "#5aa9ff",
    wear: 0.3,
  },
  {
    name: "Rusted Hauler",
    primary: "#8a6a4a",
    secondary: "#5c4a38",
    accent: "#c9b27a",
    trim: "#2a231b",
    glass: "#a8d8c8",
    emissive: "#ffb547",
    wear: 0.85,
  },
  {
    name: "Fleet Grey",
    primary: "#9aa4b2",
    secondary: "#5e6874",
    accent: "#e0e6ee",
    trim: "#22262d",
    glass: "#aee6ff",
    emissive: "#59d8ff",
    wear: 0.35,
  },
  {
    name: "Naboo Chrome",
    primary: "#d9dee5",
    secondary: "#f2c14e",
    accent: "#8c949f",
    trim: "#3d434c",
    glass: "#cfe9ff",
    emissive: "#fff0b8",
    wear: 0.05,
  },
  {
    name: "Toxic Industrial",
    primary: "#4b5a3c",
    secondary: "#2f3a26",
    accent: "#b7ff4d",
    trim: "#161b12",
    glass: "#c9ff8f",
    emissive: "#a6ff3d",
    wear: 0.7,
  },
  {
    name: "Deep Space Violet",
    primary: "#2a2340",
    secondary: "#4b3d70",
    accent: "#ff6ec7",
    trim: "#120f1c",
    glass: "#a78bff",
    emissive: "#ff6ec7",
    wear: 0.2,
  },
  {
    name: "Solar Gold",
    primary: "#f2d9a0",
    secondary: "#c99a3f",
    accent: "#7a5a1c",
    trim: "#2b2415",
    glass: "#fff3c4",
    emissive: "#ffcf5c",
    wear: 0.3,
  },
] as const;

export const PALETTE_BY_NAME: ReadonlyMap<string, Palette> = new Map(
  PALETTES.map((palette) => [palette.name, palette]),
);

export const getPalette = (name: string): Palette => PALETTE_BY_NAME.get(name) ?? DEFAULT_PALETTE;
