import type { DesignStyle, PartCategory, PartClass, PartDef, PartFinish, SnapNode, Vec3 } from "./types";
import { allNodes, type NodeOptions } from "./snap-nodes";
import { vec } from "./vec";

/**
 * Corvette module catalogue.
 *
 * Names, categories, classes and workshop prices follow the live Corvette
 * Workshop terminal (No Man's Sky "Voyagers" 6.x). The `sceneId` values follow
 * the in-game scene-node naming convention used by the ship parts
 * (`BIG_COK1X2_A`, `BIG_TRU1X1_C`, ...) — they drive both the extracted-mesh
 * loader in `src/three/ModelRegistry.ts` and the NMS Save Editor exporter.
 *
 * Stats are engineering approximations used by the shipyard's own telemetry
 * read-out; the game re-rolls real part stats per save/character.
 */

interface PartDraft {
  id: string;
  name: string;
  category: PartCategory;
  style: DesignStyle;
  archetype: string;
  size: Vec3;
  sceneId: string;
  class: PartClass;
  acquisition: "starter" | "trade" | "salvage";
  price: number | null;
  mass: number;
  power?: number;
  shield?: number;
  weapon?: number;
  cargoSlots?: number;
  speed?: number;
  manoeuvre?: number;
  boost?: number;
  tags: readonly string[];
  finish?: PartFinish;
  blurb?: string;
  nodes?: NodeOptions;
}

function definePart(draft: PartDraft): PartDef {
  const nodes: readonly SnapNode[] = allNodes(draft.size, draft.nodes ?? {});

  return {
    id: draft.id,
    name: draft.name,
    category: draft.category,
    style: draft.style,
    archetype: draft.archetype,
    size: draft.size,
    sceneId: draft.sceneId,
    itemId: draft.sceneId,
    class: draft.class,
    acquisition: draft.acquisition,
    price: draft.price,
    mass: draft.mass,
    power: draft.power ?? 0,
    shield: draft.shield ?? 0,
    weapon: draft.weapon ?? 0,
    cargoSlots: draft.cargoSlots ?? 0,
    speed: draft.speed ?? 0,
    manoeuvre: draft.manoeuvre ?? 0,
    boost: draft.boost ?? 0,
    tags: draft.tags,
    nodes,
    finish: draft.finish,
    blurb: draft.blurb,
  };
}

/** Habitation-class module node tuning: rooms chain in every direction. */
const ROOM_NODES: NodeOptions = { moduleSlots: 1, moduleSpacing: 3.4 };

/* ------------------------------------------------------------------ */
/* Cockpits                                                            */
/* ------------------------------------------------------------------ */

const COCKPITS = [
  definePart({
    id: "titan-cockpit",
    name: "Titan-Class Cockpit",
    category: "cockpit",
    style: "titan",
    archetype: "cockpit-wedge",
    size: vec(3.2, 2.6, 2.8),
    sceneId: "BIG_COK1X2_A",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 42,
    power: -18,
    speed: 4,
    manoeuvre: 8,
    boost: 14,
    tags: ["bridge", "sleek", "armoured", "titan"],
    blurb: "Armoured wedge bridge with the highest boost weighting of the three workshop cockpits.",
    nodes: { module: true, hardpoint: true, overrides: { front: { omit: true } } },
  }),
  definePart({
    id: "ambassador-cockpit",
    name: "Ambassador-Class Cockpit",
    category: "cockpit",
    style: "ambassador",
    archetype: "cockpit-dome",
    size: vec(3.0, 2.4, 2.6),
    sceneId: "BIG_COK1X2_B",
    class: "C",
    acquisition: "trade",
    price: 1_600_000,
    mass: 36,
    power: -16,
    speed: 6,
    manoeuvre: 12,
    boost: 8,
    tags: ["bridge", "agile", "curved", "ambassador"],
    blurb: "Bubble-canopy bridge. Best manoeuvrability of the workshop cockpits.",
    nodes: { module: true, hardpoint: true, overrides: { front: { omit: true } } },
  }),
  definePart({
    id: "thunderbird-cockpit",
    name: "Thunderbird-Class Cockpit",
    category: "cockpit",
    style: "thunderbird",
    archetype: "cockpit-mack",
    size: vec(3.4, 3.0, 2.6),
    sceneId: "BIG_COK1X2_D",
    class: "C",
    acquisition: "starter",
    price: 1_600_000,
    mass: 46,
    power: -20,
    speed: 3,
    manoeuvre: 6,
    boost: 6,
    tags: ["bridge", "hauler", "cab", "thunderbird"],
    blurb: "Tall freighter cab. The classic hauler nose.",
    nodes: { module: true, hardpoint: true, overrides: { front: { omit: true } } },
  }),
] as const;

/* ------------------------------------------------------------------ */
/* Habitation modules                                                  */
/* ------------------------------------------------------------------ */

const HABITATION = [
  definePart({
    id: "titan-hab",
    name: "Titan-Class Hab",
    category: "habitation",
    style: "titan",
    archetype: "hab-box",
    size: vec(3.2, 3.2, 3.2),
    sceneId: "BIG_HAB1X2_A",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 60,
    power: -12,
    cargoSlots: 3,
    tags: ["deck", "armoured", "titan", "core"],
    blurb: "Reinforced deck module. +3 cargo slots.",
    nodes: { ...ROOM_NODES, hardpoint: true, overrides: { "hp-top": { patch: { slots: 3, spacing: 1.7 } } } },
  }),
  definePart({
    id: "ambassador-hab",
    name: "Ambassador-Class Hab",
    category: "habitation",
    style: "ambassador",
    archetype: "hab-curved",
    size: vec(3.2, 3.0, 3.0),
    sceneId: "BIG_HAB1X2_C",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 52,
    power: -11,
    cargoSlots: 3,
    tags: ["deck", "curved", "ambassador", "core"],
    blurb: "Rounded habitation module with softer plating seams. +3 cargo slots.",
    nodes: { ...ROOM_NODES, hardpoint: true, overrides: { "hp-top": { patch: { slots: 3, spacing: 1.7 } } } },
  }),
  definePart({
    id: "thunderbird-hab",
    name: "Thunderbird-Class Hab",
    category: "habitation",
    style: "thunderbird",
    archetype: "hab-box",
    size: vec(3.4, 3.4, 3.0),
    sceneId: "BIG_HAB1X2_B",
    class: "B",
    acquisition: "starter",
    price: 680_000,
    mass: 64,
    power: -12,
    cargoSlots: 3,
    tags: ["deck", "hauler", "thunderbird", "core"],
    blurb: "Wide freighter deck. The backbone of every hauler build. +3 cargo slots.",
    nodes: { ...ROOM_NODES, hardpoint: true, overrides: { "hp-top": { patch: { slots: 3, spacing: 1.7 } } } },
  }),
] as const;

/* ------------------------------------------------------------------ */
/* Walkways / access modules                                           */
/* ------------------------------------------------------------------ */

const WALKWAYS = [
  definePart({
    id: "titan-walkway",
    name: "Titan-Class Walkway",
    category: "walkway",
    style: "titan",
    archetype: "walkway",
    size: vec(2.2, 2.2, 2.2),
    sceneId: "BIG_HAB1X1_A",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 22,
    power: -4,
    cargoSlots: 1,
    tags: ["corridor", "titan", "sleek"],
    blurb: "Short armoured corridor. +1 cargo slot.",
    nodes: { ...ROOM_NODES, hardpoint: true },
  }),
  definePart({
    id: "ambassador-walkway",
    name: "Ambassador-Class Walkway",
    category: "walkway",
    style: "ambassador",
    archetype: "walkway-curved",
    size: vec(2.1, 2.1, 2.1),
    sceneId: "BIG_HAB1X1_C",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 20,
    power: -4,
    cargoSlots: 1,
    tags: ["corridor", "curved", "ambassador"],
    blurb: "Rounded corridor section. +1 cargo slot.",
    nodes: { ...ROOM_NODES, hardpoint: true },
  }),
  definePart({
    id: "thunderbird-walkway",
    name: "Thunderbird-Class Walkway",
    category: "walkway",
    style: "thunderbird",
    archetype: "walkway",
    size: vec(2.3, 2.3, 2.1),
    sceneId: "BIG_HAB1X1_B",
    class: "C",
    acquisition: "starter",
    price: null,
    mass: 24,
    power: -4,
    cargoSlots: 1,
    tags: ["corridor", "hauler", "thunderbird"],
    blurb: "Wide utility corridor. +1 cargo slot.",
    nodes: { ...ROOM_NODES, hardpoint: true },
  }),
] as const;

/* ------------------------------------------------------------------ */
/* Landing bays                                                        */
/* ------------------------------------------------------------------ */

const LANDING_BAYS = [
  definePart({
    id: "titan-landing-bay",
    name: "Titan-Class Landing Bay",
    category: "landingBay",
    style: "titan",
    archetype: "landing-bay",
    size: vec(3.2, 3.0, 1.6),
    sceneId: "BIG_ALK1X1_A",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 40,
    power: -6,
    tags: ["bay", "titan", "armoured"],
    blurb: "Armoured docking ramp. Required to board and finalise the hull.",
    nodes: { module: true, hardpoint: true },
  }),
  definePart({
    id: "ambassador-landing-bay",
    name: "Ambassador-Class Landing Bay",
    category: "landingBay",
    style: "ambassador",
    archetype: "landing-bay-curved",
    size: vec(3.0, 2.8, 1.5),
    sceneId: "BIG_ALK1X1_B",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 36,
    power: -6,
    tags: ["bay", "curved", "ambassador"],
    blurb: "Curved docking ramp with integrated floodlights.",
    nodes: { module: true, hardpoint: true },
  }),
  definePart({
    id: "thunderbird-landing-bay",
    name: "Thunderbird-Class Landing Bay",
    category: "landingBay",
    style: "thunderbird",
    archetype: "landing-bay",
    size: vec(3.4, 3.2, 1.6),
    sceneId: "BIG_ALK1X1_C",
    class: "C",
    acquisition: "starter",
    price: null,
    mass: 44,
    power: -6,
    tags: ["bay", "hauler", "thunderbird"],
    blurb: "Heavy freight ramp. Wide enough to drive a rover up.",
    nodes: { module: true, hardpoint: true },
  }),
] as const;

/* ------------------------------------------------------------------ */
/* Landing gear                                                        */
/* ------------------------------------------------------------------ */

const GEAR_NODES: NodeOptions = { module: false, hardpoint: true, slots: 1 };

const LANDING_GEAR = [
  definePart({
    id: "landing-gear",
    name: "Landing Gear",
    category: "landingGear",
    style: "generic",
    archetype: "gear-strut",
    size: vec(1.6, 1.5, 1.6),
    sceneId: "BIG_LND1X1_A",
    class: "B",
    acquisition: "starter",
    price: 800_000,
    mass: 18,
    power: -2,
    tags: ["gear", "utility", "generic"],
    blurb: "Hydraulic strut with a mag-lock foot. The first part you ever place.",
    nodes: GEAR_NODES,
  }),
  definePart({
    id: "magfield-landing-thrusters",
    name: "Mag-Field Landing Thrusters",
    category: "landingGear",
    style: "generic",
    archetype: "gear-magfield",
    size: vec(1.8, 1.4, 1.8),
    sceneId: "BIG_LND1X1_B",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 20,
    power: -3,
    tags: ["gear", "sentinel", "glow"],
    blurb: "Repulsor pods with a cyan containment field.",
    nodes: GEAR_NODES,
  }),
  definePart({
    id: "hydraulic-legs",
    name: "Hydraulic Legs",
    category: "landingGear",
    style: "generic",
    archetype: "gear-quad",
    size: vec(2.0, 1.8, 2.0),
    sceneId: "BIG_LND1X1_C",
    class: "B",
    acquisition: "salvage",
    price: null,
    mass: 24,
    power: -2,
    tags: ["gear", "industrial", "heavy"],
    blurb: "Four splayed industrial legs for rough terrain.",
    nodes: GEAR_NODES,
  }),
  definePart({
    id: "thunderbird-landing-thrusters",
    name: "Thunderbird Landing Thrusters",
    category: "landingGear",
    style: "thunderbird",
    archetype: "gear-thruster",
    size: vec(1.9, 1.6, 2.4),
    sceneId: "BIG_WNG1X2_B",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 26,
    power: -4,
    speed: 1,
    tags: ["gear", "hauler", "thunderbird"],
    blurb: "Landing thruster nacelle that doubles as a hover assist.",
    nodes: GEAR_NODES,
  }),
] as const;

/* ------------------------------------------------------------------ */
/* Reactors                                                            */
/* ------------------------------------------------------------------ */

const REACTOR_NODES: NodeOptions = {
  module: true,
  hardpoint: true,
  moduleSlots: 1,
  overrides: { "hp-rear": { patch: { slots: 2, spacing: 1.9 } } },
};

const REACTORS = [
  definePart({
    id: "medusa-reactor",
    name: "Medusa-Class Reactor",
    category: "reactor",
    style: "generic",
    archetype: "reactor",
    size: vec(2.6, 2.6, 2.6),
    sceneId: "BIG_GEN1X1_1",
    class: "A",
    acquisition: "starter",
    price: 1_750_000,
    mass: 44,
    power: 40,
    manoeuvre: 18,
    tags: ["power", "flight", "core"],
    blurb: "Flight-tuned reactor. Drives the manoeuvrability tech slot.",
    nodes: REACTOR_NODES,
  }),
  definePart({
    id: "zenith-reactor",
    name: "Zenith-Class Reactor",
    category: "reactor",
    style: "generic",
    archetype: "reactor",
    size: vec(2.6, 2.6, 2.6),
    sceneId: "BIG_GEN1X1_0",
    class: "A",
    acquisition: "trade",
    price: null,
    mass: 46,
    power: 44,
    speed: 6,
    tags: ["power", "warp", "core", "exotic"],
    blurb: "Warp-tuned reactor. The one you want on an explorer.",
    nodes: REACTOR_NODES,
  }),
  definePart({
    id: "ceto-reactor",
    name: "Ceto-Class Reactor",
    category: "reactor",
    style: "generic",
    archetype: "reactor",
    size: vec(2.7, 2.7, 2.5),
    sceneId: "BIG_GEN1X1_3",
    class: "A",
    acquisition: "trade",
    price: null,
    mass: 48,
    power: 42,
    shield: 10,
    tags: ["power", "defence", "core", "armoured"],
    blurb: "Defence-tuned reactor. Feeds the shield tech slot.",
    nodes: REACTOR_NODES,
  }),
  definePart({
    id: "azimuth-reactor",
    name: "Azimuth-Class Reactor",
    category: "reactor",
    style: "generic",
    archetype: "reactor",
    size: vec(2.6, 2.8, 2.6),
    sceneId: "BIG_GEN1X1_2",
    class: "A",
    acquisition: "trade",
    price: null,
    mass: 47,
    power: 46,
    boost: 10,
    tags: ["power", "launch", "core", "combat"],
    blurb: "Launch and pulse tuned reactor.",
    nodes: REACTOR_NODES,
  }),
] as const;

/* ------------------------------------------------------------------ */
/* Thrusters                                                           */
/* ------------------------------------------------------------------ */

const THRUSTER_NODES: NodeOptions = { module: false, hardpoint: true, slots: 1 };

const THRUSTERS = [
  definePart({
    id: "titan-sublight",
    name: "Titan Sublight Thruster",
    category: "thruster",
    style: "titan",
    archetype: "thruster-nacelle",
    size: vec(1.9, 1.9, 2.6),
    sceneId: "BIG_WNG1X2_H",
    class: "B",
    acquisition: "starter",
    price: 1_400_000,
    mass: 28,
    power: -14,
    speed: 16,
    tags: ["engine", "titan", "fast"],
    blurb: "The workshop's stock sublight nacelle.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "ambassador-sublight",
    name: "Ambassador Sublight Thruster",
    category: "thruster",
    style: "ambassador",
    archetype: "thruster-curved",
    size: vec(1.8, 1.8, 2.4),
    sceneId: "BIG_WNG1X2_F",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 26,
    power: -13,
    speed: 15,
    manoeuvre: 4,
    tags: ["engine", "curved", "ambassador", "fast"],
    blurb: "Rounded nacelle with vectored nozzles.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "arcadia-sublight",
    name: "Arcadia Sublight Thruster",
    category: "thruster",
    style: "arcadia",
    archetype: "thruster-slim",
    size: vec(1.6, 1.6, 2.8),
    sceneId: "BIG_WNG1X2_L",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 24,
    power: -12,
    speed: 18,
    tags: ["engine", "sleek", "arcadia", "fast"],
    blurb: "Long, thin racer nacelle.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "twin-echo-jets",
    name: "Twin Echo Jets",
    category: "thruster",
    style: "generic",
    archetype: "thruster-twin",
    size: vec(2.2, 1.7, 2.2),
    sceneId: "BIG_TRU1X1_A",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 30,
    power: -15,
    speed: 17,
    tags: ["engine", "twin", "combat"],
    blurb: "Twin-bore jet cluster. Reads as two exhausts on one mount.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "twin-dynamo-jets",
    name: "Twin Dynamo Jets",
    category: "thruster",
    style: "generic",
    archetype: "thruster-twin",
    size: vec(2.2, 1.8, 2.1),
    sceneId: "BIG_TRU1X1_B",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 31,
    power: -16,
    speed: 16,
    manoeuvre: 3,
    tags: ["engine", "twin", "industrial"],
    blurb: "Industrial twin jets with exposed manifolds.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "twin-sublight-jet",
    name: "Twin Sublight Jet",
    category: "thruster",
    style: "generic",
    archetype: "thruster-twin",
    size: vec(2.0, 1.6, 2.2),
    sceneId: "BIG_TRU1X1_E",
    class: "B",
    acquisition: "salvage",
    price: null,
    mass: 27,
    power: -14,
    speed: 17,
    tags: ["engine", "twin", "generic"],
    blurb: "Compact twin jet for tight flanks.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "firebox-thruster",
    name: "Firebox Thruster",
    category: "thruster",
    style: "generic",
    archetype: "thruster-box",
    size: vec(2.0, 2.0, 2.0),
    sceneId: "BIG_TRU1X1_G",
    class: "B",
    acquisition: "salvage",
    price: null,
    mass: 29,
    power: -15,
    speed: 15,
    tags: ["engine", "industrial", "boxy"],
    blurb: "Squared-off thruster housing with a hot core.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "longshore-thruster",
    name: "Longshore Thruster",
    category: "thruster",
    style: "generic",
    archetype: "thruster-slim",
    size: vec(1.5, 1.5, 3.0),
    sceneId: "BIG_TRU1X1_H",
    class: "B",
    acquisition: "salvage",
    price: null,
    mass: 25,
    power: -13,
    speed: 18,
    manoeuvre: 2,
    tags: ["engine", "sleek", "long"],
    blurb: "Very long, very thin. Perfect for needle-nosed hulls.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "widebody-thruster",
    name: "Widebody Thruster",
    category: "thruster",
    style: "generic",
    archetype: "thruster-wide",
    size: vec(2.8, 1.6, 2.0),
    sceneId: "BIG_TRU1X1_F",
    class: "B",
    acquisition: "salvage",
    price: null,
    mass: 33,
    power: -17,
    speed: 19,
    tags: ["engine", "wide", "hauler"],
    blurb: "Broad single-nozzle thruster for wide hulls.",
    nodes: THRUSTER_NODES,
  }),
] as const;

/* ------------------------------------------------------------------ */
/* Main engines                                                        */
/* ------------------------------------------------------------------ */

const ENGINES = [
  definePart({
    id: "titan-heavy-booster",
    name: "Titan Heavy Booster",
    category: "engine",
    style: "titan",
    archetype: "booster",
    size: vec(2.4, 2.4, 3.2),
    sceneId: "BIG_WNG1X2_A",
    class: "A",
    acquisition: "trade",
    price: null,
    mass: 40,
    power: -22,
    speed: 26,
    tags: ["engine", "heavy", "titan", "combat"],
    blurb: "Armoured main booster.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "ambassador-heavy-booster",
    name: "Ambassador Heavy Booster",
    category: "engine",
    style: "ambassador",
    archetype: "booster-curved",
    size: vec(2.3, 2.3, 3.0),
    sceneId: "BIG_WNG1X2_C",
    class: "A",
    acquisition: "trade",
    price: null,
    mass: 38,
    power: -21,
    speed: 25,
    manoeuvre: 3,
    tags: ["engine", "heavy", "curved", "ambassador"],
    blurb: "Rounded heavy booster.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "thunderbird-heavy-booster",
    name: "Thunderbird Heavy Booster",
    category: "engine",
    style: "thunderbird",
    archetype: "booster",
    size: vec(2.6, 2.6, 3.2),
    sceneId: "BIG_WNG1X2_D",
    class: "A",
    acquisition: "trade",
    price: null,
    mass: 44,
    power: -24,
    speed: 24,
    tags: ["engine", "heavy", "hauler", "thunderbird"],
    blurb: "Big hauler booster. Slow to spool, impossible to stop.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "arcadia-heavy-booster",
    name: "Arcadia Heavy Booster",
    category: "engine",
    style: "arcadia",
    archetype: "booster-slim",
    size: vec(2.0, 2.0, 3.6),
    sceneId: "BIG_WNG1X2_N",
    class: "A",
    acquisition: "trade",
    price: null,
    mass: 36,
    power: -20,
    speed: 29,
    tags: ["engine", "heavy", "sleek", "arcadia"],
    blurb: "The fastest main engine in the workshop.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "pyrodrive-booster",
    name: "Pyrodrive Booster",
    category: "engine",
    style: "generic",
    archetype: "booster",
    size: vec(2.3, 2.3, 2.8),
    sceneId: "BIG_TRU1X1_D",
    class: "B",
    acquisition: "starter",
    price: 1_000_000,
    mass: 36,
    power: -20,
    speed: 24,
    tags: ["engine", "heavy", "starter"],
    blurb: "The stock main engine every new corvette ships with.",
    nodes: THRUSTER_NODES,
  }),
  definePart({
    id: "kineostream-thruster",
    name: "Kineostream Thruster",
    category: "engine",
    style: "generic",
    archetype: "booster-slim",
    size: vec(2.1, 2.1, 3.2),
    sceneId: "BIG_TRU1X1_C",
    class: "A",
    acquisition: "trade",
    price: null,
    mass: 34,
    power: -19,
    speed: 28,
    manoeuvre: 4,
    tags: ["engine", "heavy", "sleek", "exotic"],
    blurb: "Stream-lined main drive with a bright ion trail.",
    nodes: THRUSTER_NODES,
  }),
] as const;

/* ------------------------------------------------------------------ */
/* Defensive systems                                                   */
/* ------------------------------------------------------------------ */

const HARDPOINT_ONLY: NodeOptions = { module: false, hardpoint: true, slots: 1 };

const SHIELDS = [
  definePart({
    id: "deflector-shield",
    name: "Deflector Shield",
    category: "shield",
    style: "generic",
    archetype: "shield-disc",
    size: vec(2.4, 0.8, 2.4),
    sceneId: "BIG_SHL1X1_A",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 22,
    power: -10,
    shield: 24,
    tags: ["defence", "disc", "generic"],
    blurb: "Flat deflector emitter plate.",
    nodes: HARDPOINT_ONLY,
  }),
  definePart({
    id: "ion-barrier",
    name: "Ion Barrier",
    category: "shield",
    style: "generic",
    archetype: "shield-ring",
    size: vec(2.2, 1.0, 2.2),
    sceneId: "BIG_SHL1X1_B",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 24,
    power: -12,
    shield: 28,
    tags: ["defence", "ring", "sentinel", "glow"],
    blurb: "Ring emitter with a rotating ion field.",
    nodes: HARDPOINT_ONLY,
  }),
  definePart({
    id: "high-energy-shield",
    name: "High-Energy Shield",
    category: "shield",
    style: "generic",
    archetype: "shield-dome",
    size: vec(2.3, 1.4, 2.3),
    sceneId: "BIG_SHL1X1_C",
    class: "B",
    acquisition: "salvage",
    price: null,
    mass: 26,
    power: -14,
    shield: 34,
    tags: ["defence", "dome", "combat"],
    blurb: "Dome emitter. The toughest shield module.",
    nodes: HARDPOINT_ONLY,
  }),
  definePart({
    id: "defence-field",
    name: "Defence Field",
    category: "shield",
    style: "generic",
    archetype: "shield-disc",
    size: vec(2.6, 0.7, 2.6),
    sceneId: "BIG_SHL1X1_D",
    class: "B",
    acquisition: "salvage",
    price: null,
    mass: 25,
    power: -13,
    shield: 31,
    tags: ["defence", "disc", "industrial"],
    blurb: "Wide, thin field plate that covers a lot of hull.",
    nodes: HARDPOINT_ONLY,
  }),
] as const;

const WEAPONS = [
  definePart({
    id: "photon-cannon-array",
    name: "Photon Cannon Array",
    category: "weapon",
    style: "generic",
    archetype: "turret-cannon",
    size: vec(2.0, 1.9, 2.2),
    sceneId: "BIG_TUR1X1_A",
    class: "A",
    acquisition: "starter",
    price: 1_200_000,
    mass: 30,
    power: -16,
    weapon: 34,
    tags: ["weapon", "turret", "starter"],
    blurb: "The stock weapon mount.",
    nodes: HARDPOINT_ONLY,
  }),
  definePart({
    id: "phase-beam-array",
    name: "Phase Beam Array",
    category: "weapon",
    style: "generic",
    archetype: "turret-beam",
    size: vec(2.0, 1.7, 2.4),
    sceneId: "BIG_TUR1X1_C",
    class: "A",
    acquisition: "trade",
    price: null,
    mass: 28,
    power: -15,
    weapon: 31,
    manoeuvre: 2,
    tags: ["weapon", "beam", "sleek"],
    blurb: "Twin emitter turret with a sustained beam.",
    nodes: HARDPOINT_ONLY,
  }),
  definePart({
    id: "torpedo-launcher",
    name: "Torpedo Launcher",
    category: "weapon",
    style: "generic",
    archetype: "turret-launcher",
    size: vec(2.1, 1.6, 2.0),
    sceneId: "BIG_DECO1X1_I",
    class: "A",
    acquisition: "trade",
    price: null,
    mass: 32,
    power: -17,
    weapon: 40,
    tags: ["weapon", "launcher", "combat", "heavy"],
    blurb: "Tube launcher. Huge burst damage, slow reload.",
    nodes: HARDPOINT_ONLY,
  }),
  definePart({
    id: "deadeye-cannon",
    name: "Deadeye Cannon",
    category: "weapon",
    style: "generic",
    archetype: "turret-cannon",
    size: vec(1.8, 1.8, 2.6),
    sceneId: "BIG_TUR1X1_B",
    class: "A",
    acquisition: "salvage",
    price: null,
    mass: 29,
    power: -16,
    weapon: 37,
    tags: ["weapon", "cannon", "combat"],
    blurb: "Long-barrel precision cannon.",
    nodes: HARDPOINT_ONLY,
  }),
  definePart({
    id: "cyclotron-defence-cannon",
    name: "Cyclotron Defence Cannon",
    category: "weapon",
    style: "generic",
    archetype: "turret-cyclotron",
    size: vec(2.2, 2.0, 2.2),
    sceneId: "BIG_TUR1X1_D",
    class: "A",
    acquisition: "salvage",
    price: null,
    mass: 34,
    power: -19,
    weapon: 36,
    shield: 6,
    tags: ["weapon", "defence", "combat", "sentinel"],
    blurb: "Point-defence cannon that also intercepts incoming fire.",
    nodes: HARDPOINT_ONLY,
  }),
  definePart({
    id: "infra-knife-platform",
    name: "Infra-Knife Platform",
    category: "weapon",
    style: "generic",
    archetype: "turret-platform",
    size: vec(2.4, 1.5, 2.4),
    sceneId: "BIG_TUR1X1_E",
    class: "A",
    acquisition: "salvage",
    price: null,
    mass: 31,
    power: -18,
    weapon: 38,
    tags: ["weapon", "platform", "combat", "exotic"],
    blurb: "Rotating platform carrying an infra-knife accelerator.",
    nodes: HARDPOINT_ONLY,
  }),
] as const;

/* ------------------------------------------------------------------ */
/* Wings & foils                                                       */
/* ------------------------------------------------------------------ */

const FOIL_NODES: NodeOptions = { module: false, hardpoint: true, slots: 1 };

const WINGS = [
  definePart({
    id: "arcadia-sfoil",
    name: "Arcadia S-Foil",
    category: "wing",
    style: "arcadia",
    archetype: "foil-s",
    size: vec(2.6, 0.45, 4.6),
    sceneId: "BIG_WNG1X2_I",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 18,
    power: -3,
    manoeuvre: 12,
    tags: ["wing", "sleek", "arcadia", "s-foil"],
    blurb: "The classic S-foil. Reads instantly as a fighter wing.",
    nodes: FOIL_NODES,
  }),
  definePart({
    id: "arcadia-wing-module",
    name: "Arcadia Wing Module",
    category: "wing",
    style: "arcadia",
    archetype: "foil-flat",
    size: vec(2.8, 0.5, 4.2),
    sceneId: "BIG_WNG1X2_J",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 19,
    power: -3,
    manoeuvre: 11,
    tags: ["wing", "flat", "arcadia", "panel"],
    blurb: "Flat solar-panel wing. Perfect TIE-fighter surface.",
    nodes: FOIL_NODES,
  }),
  definePart({
    id: "arcadia-aerofoil",
    name: "Arcadia Aerofoil",
    category: "wing",
    style: "arcadia",
    archetype: "foil-tapered",
    size: vec(2.4, 0.4, 4.0),
    sceneId: "BIG_WNG1X2_K",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 16,
    power: -2,
    speed: 4,
    manoeuvre: 10,
    tags: ["wing", "sleek", "arcadia", "tapered"],
    blurb: "Tapered high-speed foil.",
    nodes: FOIL_NODES,
  }),
  definePart({
    id: "ambassador-wing-module",
    name: "Ambassador Wing Module",
    category: "wing",
    style: "ambassador",
    archetype: "foil-curved",
    size: vec(2.5, 0.6, 4.0),
    sceneId: "BIG_WNG1X2_M",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 18,
    power: -3,
    manoeuvre: 11,
    tags: ["wing", "curved", "ambassador"],
    blurb: "Softly curved wing with a swept tip.",
    nodes: FOIL_NODES,
  }),
  definePart({
    id: "osprey-wing-module",
    name: "Osprey Wing Module",
    category: "wing",
    style: "generic",
    archetype: "foil-swept",
    size: vec(3.0, 0.55, 4.4),
    sceneId: "BIG_WNG1X2_E",
    class: "B",
    acquisition: "salvage",
    price: null,
    mass: 20,
    power: -3,
    manoeuvre: 13,
    tags: ["wing", "swept", "gunship"],
    blurb: "Swept wing that reads as a gunship or quinjet surface.",
    nodes: FOIL_NODES,
  }),
  definePart({
    id: "titan-wing-module",
    name: "Titan Wing Module",
    category: "wing",
    style: "titan",
    archetype: "foil-armoured",
    size: vec(2.7, 0.8, 4.2),
    sceneId: "BIG_WNG1X2_G",
    class: "B",
    acquisition: "trade",
    price: null,
    mass: 24,
    power: -3,
    shield: 6,
    manoeuvre: 8,
    tags: ["wing", "armoured", "titan", "combat"],
    blurb: "Thick armoured wing. Also works as a flying buttress.",
    nodes: FOIL_NODES,
  }),
  definePart({
    id: "rockhopper-wing-module",
    name: "Rockhopper Wing Module",
    category: "wing",
    style: "rockhopper",
    archetype: "foil-ragged",
    size: vec(2.6, 0.7, 4.0),
    sceneId: "BIG_WNG1X2_O_0",
    class: "B",
    acquisition: "salvage",
    price: null,
    mass: 21,
    power: -3,
    manoeuvre: 9,
    tags: ["wing", "ragged", "rockhopper", "industrial"],
    blurb: "Salvaged, asymmetric wing with exposed ribs.",
    nodes: FOIL_NODES,
  }),
  definePart({
    id: "rockhopper-propeller-module",
    name: "Rockhopper Propeller Module",
    category: "wing",
    style: "rockhopper",
    archetype: "foil-prop",
    size: vec(2.2, 1.6, 3.4),
    sceneId: "BIG_WNG1X2_O_1",
    class: "B",
    acquisition: "salvage",
    price: null,
    mass: 23,
    power: -5,
    manoeuvre: 8,
    tags: ["wing", "rotor", "rockhopper", "exotic"],
    blurb: "Rotating vane assembly. Great for vertical-axis hulls.",
    nodes: FOIL_NODES,
  }),
  definePart({
    id: "rockhopper-fin-module",
    name: "Rockhopper Fin Module",
    category: "wing",
    style: "rockhopper",
    archetype: "foil-fin",
    size: vec(0.6, 3.0, 3.0),
    sceneId: "BIG_WNG1X2_O_2",
    class: "B",
    acquisition: "salvage",
    price: null,
    mass: 17,
    power: -2,
    manoeuvre: 7,
    tags: ["wing", "fin", "vertical", "rockhopper"],
    blurb: "Tall vertical fin / rudder.",
    nodes: FOIL_NODES,
  }),
] as const;

/* ------------------------------------------------------------------ */
/* Hull plating & structural decoration                                */
/* ------------------------------------------------------------------ */

const PLATE_NODES: NodeOptions = { module: false, hardpoint: true, slots: 1 };

const PLATING = [
  definePart({
    id: "argonaut-cowling",
    name: "Argonaut Cowling",
    category: "plating",
    style: "argonaut",
    archetype: "plate-cowl",
    size: vec(2.4, 2.4, 0.6),
    sceneId: "BIG_STR1X1_A",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 16,
    shield: 8,
    tags: ["plating", "armour", "argonaut"],
    blurb: "Armoured cowling that shields whatever sits behind it.",
    nodes: PLATE_NODES,
  }),
  definePart({
    id: "supercruise-cowling",
    name: "Supercruise Cowling",
    category: "plating",
    style: "supercruise",
    archetype: "plate-cowl",
    size: vec(2.3, 2.3, 0.55),
    sceneId: "BIG_STR1X1_B",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 15,
    shield: 7,
    speed: 2,
    tags: ["plating", "sleek", "supercruise"],
    blurb: "Streamlined cowling with intake scoops.",
    nodes: PLATE_NODES,
  }),
  definePart({
    id: "hardframe-cowling",
    name: "Hardframe Cowling",
    category: "plating",
    style: "hardframe",
    archetype: "plate-frame",
    size: vec(2.5, 2.5, 0.7),
    sceneId: "BIG_STR1X1_C",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 19,
    shield: 11,
    tags: ["plating", "armour", "hardframe", "industrial"],
    blurb: "Ribbed structural frame. Exposed-girder aesthetic.",
    nodes: PLATE_NODES,
  }),
  definePart({
    id: "argonaut-aerofoil",
    name: "Argonaut Aerofoil",
    category: "plating",
    style: "argonaut",
    archetype: "plate-foil",
    size: vec(2.2, 0.4, 3.4),
    sceneId: "BIG_STR1X1_D",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 12,
    manoeuvre: 6,
    tags: ["plating", "foil", "argonaut", "sleek"],
    blurb: "Thin armour foil. Doubles as a stabiliser.",
    nodes: PLATE_NODES,
  }),
  definePart({
    id: "argonaut-winglet",
    name: "Argonaut Winglet",
    category: "plating",
    style: "argonaut",
    archetype: "plate-winglet",
    size: vec(1.4, 2.0, 2.2),
    sceneId: "BIG_STR1X1_E",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 10,
    manoeuvre: 5,
    tags: ["plating", "winglet", "argonaut"],
    blurb: "Small upturned winglet for tail surfaces.",
    nodes: PLATE_NODES,
  }),
  definePart({
    id: "supercruise-aerofoil",
    name: "Supercruise Aerofoil",
    category: "plating",
    style: "supercruise",
    archetype: "plate-foil",
    size: vec(2.1, 0.4, 3.2),
    sceneId: "BIG_STR1X1_F",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 11,
    speed: 3,
    manoeuvre: 6,
    tags: ["plating", "foil", "supercruise", "sleek"],
    blurb: "Curved aerofoil for fast hulls.",
    nodes: PLATE_NODES,
  }),
  definePart({
    id: "albatross-sidepod",
    name: "Albatross Sidepod",
    category: "plating",
    style: "albatross",
    archetype: "pod-side",
    size: vec(1.6, 1.8, 3.0),
    sceneId: "BIG_STR1X1_K_N",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 17,
    shield: 6,
    tags: ["plating", "pod", "albatross", "industrial"],
    blurb: "Flank-mounted pod. Instant gunship silhouette.",
    nodes: PLATE_NODES,
  }),
  definePart({
    id: "albatross-cargo-tank",
    name: "Albatross Cargo Tank",
    category: "cargo",
    style: "albatross",
    archetype: "tank",
    size: vec(1.8, 1.8, 3.2),
    sceneId: "BIG_STR1X1_L_N",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 20,
    cargoSlots: 2,
    tags: ["cargo", "tank", "albatross", "industrial"],
    blurb: "Cylindrical external tank. +2 cargo slots.",
    nodes: PLATE_NODES,
  }),
  definePart({
    id: "arcadia-blade",
    name: "Arcadia Blade",
    category: "plating",
    style: "arcadia",
    archetype: "plate-blade",
    size: vec(1.0, 1.6, 3.4),
    sceneId: "BIG_STR1X1_K_NE",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 9,
    speed: 2,
    manoeuvre: 4,
    tags: ["plating", "blade", "arcadia", "sleek"],
    blurb: "Knife-thin blade panel. Perfect for wedges and rams.",
    nodes: PLATE_NODES,
  }),
  definePart({
    id: "hull-plate-flat",
    name: "Flat Hull Plate",
    category: "plating",
    style: "generic",
    archetype: "plate-flat",
    size: vec(2.4, 2.4, 0.35),
    sceneId: "BIG_STR1X1_G",
    class: "C",
    acquisition: "salvage",
    price: null,
    mass: 8,
    shield: 4,
    tags: ["plating", "flat", "panel", "generic"],
    blurb: "Plain armour plate. The workhorse of every silhouette.",
    nodes: PLATE_NODES,
  }),
  definePart({
    id: "hull-plate-angled",
    name: "Angled Hull Plate",
    category: "plating",
    style: "generic",
    archetype: "plate-angled",
    size: vec(2.4, 2.0, 0.9),
    sceneId: "BIG_STR1X1_H",
    class: "C",
    acquisition: "salvage",
    price: null,
    mass: 10,
    shield: 6,
    tags: ["plating", "angled", "sentinel", "combat"],
    blurb: "Bevelled plate. The key to faceted Sentinel hulls.",
    nodes: PLATE_NODES,
  }),
] as const;

/* ------------------------------------------------------------------ */
/* Cargo attachments & structural detail                               */
/* ------------------------------------------------------------------ */

const CARGO = [
  definePart({
    id: "cargo-capsule",
    name: "Cargo Capsule",
    category: "cargo",
    style: "generic",
    archetype: "cargo-capsule",
    size: vec(1.6, 1.6, 2.4),
    sceneId: "BIG_STR1X1_I",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 16,
    cargoSlots: 2,
    tags: ["cargo", "capsule", "industrial"],
    blurb: "Pressurised cargo capsule. +2 cargo slots.",
    nodes: PLATE_NODES,
  }),
  definePart({
    id: "cargo-pod",
    name: "Cargo Pod",
    category: "cargo",
    style: "generic",
    archetype: "cargo-box",
    size: vec(2.0, 2.0, 2.0),
    sceneId: "BIG_STR1X1_J",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 18,
    cargoSlots: 2,
    tags: ["cargo", "box", "industrial", "container"],
    blurb: "Cubic container. Stack them for a Nostromo look. +2 cargo slots.",
    nodes: { module: true, hardpoint: true, slots: 1 },
  }),
  definePart({
    id: "cargo-sphere",
    name: "Cargo Sphere",
    category: "cargo",
    style: "generic",
    archetype: "cargo-sphere",
    size: vec(2.2, 2.2, 2.2),
    sceneId: "BIG_STR1X1_M",
    class: "C",
    acquisition: "trade",
    price: null,
    mass: 19,
    cargoSlots: 2,
    tags: ["cargo", "sphere", "exotic"],
    blurb: "Spherical tank. Great for organic and exotic hulls. +2 cargo slots.",
    nodes: { module: true, hardpoint: true, slots: 1 },
  }),
] as const;

const DETAIL = [
  definePart({
    id: "sensor-mast",
    name: "Sensor Mast",
    category: "decoration",
    style: "generic",
    archetype: "mast",
    size: vec(0.5, 2.6, 0.5),
    sceneId: "BIG_DECO1X1_A",
    class: "C",
    acquisition: "salvage",
    price: null,
    mass: 5,
    power: -1,
    tags: ["detail", "sensor", "vertical"],
    blurb: "Tall sensor mast with a rotating dish.",
    nodes: HARDPOINT_ONLY,
  }),
  definePart({
    id: "comm-array",
    name: "Comm Array",
    category: "decoration",
    style: "generic",
    archetype: "antenna",
    size: vec(1.6, 1.2, 0.6),
    sceneId: "BIG_DECO1X1_B",
    class: "C",
    acquisition: "salvage",
    price: null,
    mass: 4,
    power: -1,
    tags: ["detail", "antenna", "industrial"],
    blurb: "Flat phased antenna panel.",
    nodes: HARDPOINT_ONLY,
  }),
  definePart({
    id: "vent-stack",
    name: "Vent Stack",
    category: "decoration",
    style: "generic",
    archetype: "vent",
    size: vec(1.2, 1.0, 1.2),
    sceneId: "BIG_DECO1X1_C",
    class: "C",
    acquisition: "salvage",
    price: null,
    mass: 6,
    tags: ["detail", "vent", "industrial"],
    blurb: "Heat vent cluster with glowing louvres.",
    nodes: HARDPOINT_ONLY,
  }),
  definePart({
    id: "floodlight-rig",
    name: "Floodlight Rig",
    category: "decoration",
    style: "generic",
    archetype: "lights",
    size: vec(1.6, 0.6, 0.6),
    sceneId: "BIG_DECO1X1_D",
    class: "C",
    acquisition: "salvage",
    price: null,
    mass: 4,
    power: -1,
    tags: ["detail", "lights", "utility"],
    blurb: "Row of exterior floodlights.",
    nodes: HARDPOINT_ONLY,
  }),
] as const;

export const PARTS: readonly PartDef[] = [
  ...COCKPITS,
  ...HABITATION,
  ...WALKWAYS,
  ...LANDING_BAYS,
  ...LANDING_GEAR,
  ...REACTORS,
  ...THRUSTERS,
  ...ENGINES,
  ...SHIELDS,
  ...WEAPONS,
  ...WINGS,
  ...PLATING,
  ...CARGO,
  ...DETAIL,
] as const;

export const PART_BY_ID: ReadonlyMap<string, PartDef> = new Map(PARTS.map((part) => [part.id, part]));

export const getPart = (id: string): PartDef => {
  const part = PART_BY_ID.get(id);
  if (!part) throw new Error(`Unknown corvette part id: "${id}"`);
  return part;
};

export const tryGetPart = (id: string): PartDef | undefined => PART_BY_ID.get(id);

export const partsByCategory = (category: PartCategory): PartDef[] =>
  PARTS.filter((part) => part.category === category);

export const partsByStyle = (style: DesignStyle): PartDef[] =>
  PARTS.filter((part) => part.style === style);

export const partsByTag = (tag: string): PartDef[] => PARTS.filter((part) => part.tags.includes(tag));

export const PART_COUNT = PARTS.length;
